### ISSUE TITLE
使用命令面板，回车无法打开面板，alt+s 可以，点击可以

### ISSUE THREAD

**Issue by akkuman** [frostime/sy-doc-context#1]
首先使用 alt+shift + p 搜索上下文找到插件
![image](https://github.com/user-attachments/assets/0b93549b-92eb-40db-aa74-4952f9d62e73)

使用回车没有反应

点击可以唤起面板

alt+s 可以唤起面板

**Comment by akkuman** [comment]
上面是客户端

在手机浏览器中打开命令面板搜索，然后点击，似乎无法唤起

**Comment by akkuman** [comment]
@frostime 好像手机浏览器打开命令面板，搜索上下文，点击，还是不会弹出
pc 端也是打开命令面板，搜索上下文，回车，不会弹出

**Comment by frostime** [comment]
我测试了一下，PC 端命令面板里面如果是点击就能弹出，但是如果是 Enter 键就无法触发。具体原因不明，怀疑是思源的问题。

**Comment by akkuman** [comment]
https://github.com/siyuan-note/siyuan/issues/12816 已修复

**Comment by frostime** [comment]
> [siyuan-note/siyuan#12816](https://github.com/siyuan-note/siyuan/issues/12816) 已修复

感谢贡献 issue。
