### ISSUE TITLE
允许自定义父子文档快捷键，避免和内置快捷键的冲突

### ISSUE THREAD

**Issue by Zonezzc** [frostime/sy-doc-context#2]
操作步骤
1. 关闭文档上下文插件
2. 快捷键-编辑器-通用：展开、折叠，设置任意快捷键，快捷键正常触发
3. 开启文档上下文插件
4. 展开、折叠快捷键失效，查看设置中的快捷键配置，发现设置的展开、折叠快捷键被重置为空

思源笔记版本
v3.1.13
操作系统
mac m1

**Comment by frostime** [comment]
![image](https://github.com/user-attachments/assets/36346d47-d6bd-4d2a-bf7c-e5c14fd2323c)

这个问题我在文档里面已经说明过了。你可以在插件设置中把这个关掉。

![image](https://github.com/user-attachments/assets/d1589dfd-e562-4bea-8331-aa3dffb75185)

**Comment by Zonezzc** [comment]
不好意思，确实没注意到，是目前只能这样吗？期望的效果是展开折叠可以设置其他快捷键位，在设置其他键位之后不被覆盖掉。

**Comment by frostime** [comment]
后面增加一下快捷键配置吧。

**Comment by Zonezzc** [comment]
感谢大佬！
